import { NamedEntity } from 'src/modules/shared/domain/entities/named-entity';
import { CharacterAttack } from '../value-objects/character-attack.vo';
import { CharacterDefense } from '../value-objects/character-defense.vo';
import { CharacterEndurance } from '../value-objects/character-endurance.vo';
import { CharacterEquipment } from '../value-objects/character-equipment.vo';
import { CharacterHP } from '../value-objects/character-hp.vo';
import { CharacterInfo } from '../value-objects/character-info.vo';
import { CharacterInitiative } from '../value-objects/character-initiative.vo';
import { CharacterMovement } from '../value-objects/character-movement.vo';
import { CharacterPower } from '../value-objects/character-power.vo';
import { CharacterResistance } from '../value-objects/character-resistances.vo';
import { CharacterRoleplayInfo } from '../value-objects/character-roleplay-info.vo';
import { CharacterSkill } from '../value-objects/character-skill.vo';
import { CharacterStat, StatKey } from '../value-objects/character-stat.vo';
import { CharacterStatus } from '../value-objects/character-status.vo';
import { CharacterTrait } from '../value-objects/character-trait.vo';
import { CharacterXP } from '../value-objects/character-xp.vo';

export interface CharacterProps {
  id: string;
  gameId: string;
  faction: NamedEntity;
  name: string;
  info: CharacterInfo;
  roleplay: CharacterRoleplayInfo;
  experience: CharacterXP;
  statistics: Record<StatKey, CharacterStat>;
  movement: CharacterMovement;
  defense: CharacterDefense;
  resistances: CharacterResistance[];
  hp: CharacterHP;
  endurance: CharacterEndurance;
  power: CharacterPower | null;
  initiative: CharacterInitiative;
  skills: CharacterSkill[];
  equipment: CharacterEquipment;
  attacks: CharacterAttack[];
  traits: CharacterTrait[];
  status: CharacterStatus;
  description: string | undefined;
  imageUrl: string | undefined;
  owner: string;
  createdAt: Date;
  updatedAt: Date | undefined;
}
